
/* The Is-A group of Employee based Entities */
CREATE TABLE Employee (
	Eid		INTEGER,
	Name	CHAR[50],
	Phnext	INTEGER,
	PRIMARY KEY (Eid) )

CREATE TABLE Technical (
	Eid 		INTEGER,
	Speciality	CHAR[50],
	PRIMARY KEY (Eid),
	FOREIGN KEY (Eid) REFERENCES Employee )

CREATE TABLE Admin (
	Eid		INTEGER,
	Grade	INTEGER,
	PRIMARY KEY (Eid),
	FOREIGN KEY (Eid) REFERENCES Employee )

/* The other Entities */
CREATE TABLE Project (
	Id	INTEGER,
	Name	CHAR[50],
	Budget	FLOAT,
	PRIMARY KEY (Id),
	FOREIGN KEY (Id) REFERENCES WorksOn )
	
CREATE TABLE Supplier (
	SId	INTEGER,
	Name	CHAR[50],
	PRIMARY KEY (SId) )

CREATE TABLE Part (
	PId	INTEGER,
	Name	CHAR[50],
	PRIMARY KEY (PId),
	FOREIGN KEY (PId) REFERENCES Has )

CREATE TABLE PurchaseOrder (
	POId	INTEGER,
	PRIMARY KEY (POId),
	FOREIGN KEY (POId) REFERENCES Approves )

CREATE TABLE Depts (
	DId	INTEGER,
	Name	CHAR[50],
	Budget	FLOAT,
	PRIMARY KEY (DId),
	FOREIGN KEY (DId) REFERENCES Manages )


/* The Relationships */
CREATE TABLE WorksOn (
	Eid	INTEGER,
	Id	INTEGER,
	PRIMARY KEY (Eid, Id),
	FOREIGN KEY (Eid) REFERENCES Technical,
	FOREIGN KEY (Id) REFERENCES Project )

CREATE TABLE Sponsors (
	SId	INTEGER,
	Id	INTEGER,
	Funding	FLOAT,
	PRIMARY KEY (SId, Id),
	FOREIGN KEY (SId) REFERENCES Supplier,
	FOREIGN KEY (Id) REFERENCES Project )

CREATE TABLE SBy (
	PId	INTEGER,
	SId	INTEGER,
	Price	INTEGER,
	PRIMARY KEY (PId, SId),
	FOREIGN KEY (PId) REFERENCES Part,
	FOREIGN KEY (SId) REFERENCES Supplier )

CREATE TABLE Has (
	POId	INTEGER,
	PId	INTEGER,
	PRIMARY KEY (PId),
	FOREIGN KEY (POId) REFERENCES PurchaseOrder,
	FOREIGN KEY (PId) REFERENCES Part )

CREATE TABLE Places (
	Eid	INTEGER,
	POId	INTEGER,
	PRIMARY KEY (POId),
	FOREIGN KEY (Eid) REFERENCES Technical,
	FOREIGN KEY (POId) REFERENCES PurchaseOrder )

CREATE TABLE Approves (
	Eid	INTEGER,
	POId	INTEGER,
	PRIMARY KEY (POId),
	FOREIGN KEY (Eid) REFERENCES Admin,
	FOREIGN KEY (POId) REFERENCES PurchaseOrder )

CREATE TABLE IsAt (
	Eid	INTEGER,
	DId	INTEGER,
	PRIMARY KEY (Eid),
	FOREIGN KEY (Eid) REFERENCES Admin,
	FOREIGN KEY (DId) REFERENCES Depts )
	
CREATE TABLE Manages (
	Eid	INTEGER,
	DId	INTEGER,
	PRIMARY KEY (DId),
	FOREIGN KEY (Eid) REFERENCES Admin,
	FOREIGN KEY (DId) REFERENCES Depts )